### ISSUE TITLE
fixed value tier prices converted to integer

### ISSUE THREAD

**Issue by ktruehl** [techdivision/import-product-tier-price#6]
Hello again!

I finally got around to upgrading to the latest release of the M2IF. Thanks so much for including the tier price import in the M2IF.

I did quite a bit of testing and it looks great so far. There are two issues, one is rather straight forward.

In `src/Observers/PrepareTierPriceTrait.php` on line 82 you convert the value to integer, even if the price type is "fixed".

Here our composer patch: 
[bugfix-[2.0]--do-not-convert-tier-price-to-integer.diff.zip](https://github.com/techdivision/import-product-tier-price/files/3182221/bugfix-.2.0.--do-not-convert-tier-price-to-integer.diff.zip)

For the other problem I will create a separate issue.

Best,
Klaas

**Comment by wagnert** [comment]
@ktruehl Thanks for the patch, will be released with the next version :-)
